# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\ngrpcThesis\"1\n\nTensorList\x12#\n\x07tensors\x18\x01 \x03(\x0b\x32\x12.grpcThesis.Tensor\"%\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\"=\n\rServerMessage\x12,\n\x0clist_tensors\x18\x01 \x01(\x0b\x32\x16.grpcThesis.TensorList\"e\n\rClientMessage\x12\x11\n\tclient_id\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x61ta_length\x18\x01 \x01(\x05\x12,\n\x0clist_tensors\x18\x02 \x01(\x0b\x32\x16.grpcThesis.TensorList\"\x16\n\x05\x45mpty\x12\r\n\x05value\x18\x01 \x01(\x05\"\x18\n\x07IsReady\x12\r\n\x05ready\x18\x01 \x01(\x08\x32\xde\x01\n\x11\x46\x65\x64\x65ratedLearning\x12:\n\x0eIsWeightsReady\x12\x11.grpcThesis.Empty\x1a\x13.grpcThesis.IsReady\"\x00\x12\x46\n\x17GetAvgWeightsFromServer\x12\x11.grpcThesis.Empty\x1a\x16.grpcThesis.TensorList\"\x00\x12\x45\n\x13SendWeightsToServer\x12\x19.grpcThesis.ClientMessage\x1a\x11.grpcThesis.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TENSORLIST._serialized_start=29
  _TENSORLIST._serialized_end=78
  _TENSOR._serialized_start=80
  _TENSOR._serialized_end=117
  _SERVERMESSAGE._serialized_start=119
  _SERVERMESSAGE._serialized_end=180
  _CLIENTMESSAGE._serialized_start=182
  _CLIENTMESSAGE._serialized_end=283
  _EMPTY._serialized_start=285
  _EMPTY._serialized_end=307
  _ISREADY._serialized_start=309
  _ISREADY._serialized_end=333
  _FEDERATEDLEARNING._serialized_start=336
  _FEDERATEDLEARNING._serialized_end=558
# @@protoc_insertion_point(module_scope)
